baseURL = 'https://rrnotes.github.io/'
title = 'Notes'
theme = 'hugo-book'

[markup.godmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'dark'
  BookSection = '/'