baseURL = 'https://roundrobin792.github.io/rrnotes/'
title = 'Notes'
theme = 'hugo-book'
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block  = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.renderer]
        unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'light'
  BookSection = '/'