baseURL = 'https://roundrobin792.github.io/rrnotes/'
title = 'Notes'
theme = 'hugo-book'
pluralizeListTitles = false

[markup.godmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookTheme = 'light'
  BookSection = '/'